clean:
		find ./ -name '*debuglog*' -delete
		find ./ -name '*.st0' -delete
		find ./ -name '*.tr0' -delete
		find ./ -name '*.sw0' -delete
		find ./ -name 'sxcmd.*' -delete
		find ./ -name '*.pvadir' -delete
		find ./ -name '*.pvadir' -exec rm -rf {} \;
